#!/bin/sh

echo "HD-720p-device3"

killall -9 decklinkcapture3d jackd

/home/toand/git/sage-dev/app/decklinkcapture3d/decklinkcapture3D -d 2 -m 15 -i 2 -v
#/home/toand/git/sage-dev/app/decklinkcapture3d/decklinkcapture3D -d 2 -m 15 -i 2 -v -b
# -b: use SBS stereo